<div class="field">
  <div class="two columns alpha">
    <label for="css"><?php echo $this->translate('CSS'); ?></label>
  </div>
  <div class="inputs five columns omega">
    <p class="explanation">
      <?php echo $this->translate('Add custom CSS for sites.'); ?><br/>
      <?php echo $this->translate("Note: CSS rules defined for 'Default' will only be used if no CSS is defined for a specific site in this module."); ?><br/>
      <?php echo $this->translate('Warning: the following tags cannot be used in selectors:'); ?>
      <b>body, head, html</b>.<br/>
      <?php echo sprintf($this->translate('For instance, if you define a rule like %s, it will be removed when submitting your changes.'), '<code>body {color: red;}</code>'); ?>
    </p>
    <div id="csseditor_site">
      <?php
        echo $this->siteSelect()
          ->setEmptyOption($this->translate('Default'))
          ->render('site');
      ?>
    </div>
    <div>
      <?php echo $this->formTextarea($textarea); ?>
    </div>

  </div>
<br/>
<a href='#'  onclick="return saveCss();return false">Save</a>
</div>


<script>
 var prev_data= $('#csseditor_cssvalue').val();
 var prev_site_id=$('#csseditor_site select').val();

function saveCss() {
   var site_id = $('#csseditor_site select').val();
   var base_url = '<?php echo $this->url('admin/csseditor'); ?>';
   var current_val=$('#csseditor_cssvalue').val();
   var url = base_url;

   if (site_id >0) {
     url = base_url + '/' + site_id;
   }

   $.post(url, { 'css': current_val,
                 'site' : prev_site_id})
         .fail(function(data) {
       alert(data.responseText);
     $('#csseditor_site select').val(prev_site_id);

   })
         .done(function(data) {
     $('#csseditor_cssvalue').val(data);
     prev_data=data;
     prev_site_id=site_id;
     alert('Css saved');
   });

 }


 $("#csseditor_site select").change(function() {
   var site_id = $(this).val();
   var base_url = '<?php echo $this->url('admin/csseditor'); ?>';
   var url = base_url;
   if (site_id >0) {
     url = base_url + '/' + site_id;
   }

   var current_val=$('#csseditor_cssvalue').val();

   if (prev_data != current_val) {
     if (confirm('<?php echo $this->translate('Do you want to save before switching ?') ?>') == true) {
     $.post(url, { 'css': current_val,
                                    'site' : prev_site_id})
         .fail(function(data) {
       alert(data.responseText);
       $('#csseditor_site select').val(prev_site_id);



     })
         .done(function(data) {
       $('#csseditor_cssvalue').val(data);
       prev_data=data;
       prev_site_id=site_id;
     });

   }
else {     $('#csseditor_site select').val(prev_site_id);}
}
   else {

     $.ajax({
       'url' : url,
       'type': 'get',
       'success': function(data) {
         $('#csseditor_cssvalue').val(data);
         prev_data=data;
         prev_site_id=site_id;
       }
     });
   }
 });
</script>
