<div class="field">
    <div class="two columns alpha">
        <label for="css"><?php echo $translator->translate('CSS'); ?></label>
    </div>
    <div class="inputs five columns omega">
        <p class="explanation"><?php echo $translator->translate('The custom CSS you would like to add.'); ?></p>
        <div class="input-block">
            <?php echo $this->formTextarea($textarea); ?>
        </div>
    </div>
</div>
